"use strict";

module.exports = {
   async up(queryInterface, Sequelize) {
      await queryInterface.bulkInsert("events", [
         {
            name: "Tech Conference",
            description: "A conference for technology enthusiasts",
            startDate: "2024-02-01",
            endDate: "2024-02-02",
            country: "United States",
            city: "San Francisco",
            maxMembers: 500,
            price: 200,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Music Festival",
            description: "Annual music festival featuring various artists",
            startDate: "2024-03-15",
            endDate: "2024-03-17",
            country: "United Kingdom",
            city: "London",
            maxMembers: 1000,
            price: 50,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Sports Event",
            description: "International sports competition",
            startDate: "2024-04-20",
            endDate: "2024-04-21",
            country: "Brazil",
            city: "Rio de Janeiro",
            maxMembers: 300,
            price: 100,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Tech Conference",
            description: "A conference for technology enthusiasts",
            startDate: "2024-02-01",
            endDate: "2024-02-02",
            country: "United States",
            city: "San Francisco",
            maxMembers: 500,
            price: 200,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Music Festival",
            description: "Annual music festival featuring various artists",
            startDate: "2024-03-15",
            endDate: "2024-03-17",
            country: "United Kingdom",
            city: "London",
            maxMembers: 1000,
            price: 50,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Sports Event",
            description: "International sports competition",
            startDate: "2024-04-20",
            endDate: "2024-04-21",
            country: "Brazil",
            city: "Rio de Janeiro",
            maxMembers: 300,
            price: 100,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Tech Conference",
            description: "A conference for technology enthusiasts",
            startDate: "2024-02-01",
            endDate: "2024-02-02",
            country: "United States",
            city: "San Francisco",
            maxMembers: 500,
            price: 200,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Music Festival",
            description: "Annual music festival featuring various artists",
            startDate: "2024-03-15",
            endDate: "2024-03-17",
            country: "United Kingdom",
            city: "London",
            maxMembers: 1000,
            price: 50,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Sports Event",
            description: "International sports competition",
            startDate: "2024-04-20",
            endDate: "2024-04-21",
            country: "Brazil",
            city: "Rio de Janeiro",
            maxMembers: 300,
            price: 100,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Tech Conference",
            description: "A conference for technology enthusiasts",
            startDate: "2024-02-01",
            endDate: "2024-02-02",
            country: "United States",
            city: "San Francisco",
            maxMembers: 500,
            price: 200,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Music Festival",
            description: "Annual music festival featuring various artists",
            startDate: "2024-03-15",
            endDate: "2024-03-17",
            country: "United Kingdom",
            city: "London",
            maxMembers: 1000,
            price: 50,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Sports Event",
            description: "International sports competition",
            startDate: "2024-04-20",
            endDate: "2024-04-21",
            country: "Brazil",
            city: "Rio de Janeiro",
            maxMembers: 300,
            price: 100,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Tech Conference",
            description: "A conference for technology enthusiasts",
            startDate: "2024-02-01",
            endDate: "2024-02-02",
            country: "United States",
            city: "San Francisco",
            maxMembers: 500,
            price: 200,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Music Festival",
            description: "Annual music festival featuring various artists",
            startDate: "2024-03-15",
            endDate: "2024-03-17",
            country: "United Kingdom",
            city: "London",
            maxMembers: 1000,
            price: 50,
            image: "/assets/images/events/event-1.jpg",
         },
         {
            name: "Sports Event",
            description: "International sports competition",
            startDate: "2024-04-20",
            endDate: "2024-04-21",
            country: "Brazil",
            city: "Rio de Janeiro",
            maxMembers: 300,
            price: 100,
            image: "/assets/images/events/event-1.jpg",
         },
      ]);
   },

   async down(queryInterface, Sequelize) {
      await queryInterface.bulkDelete("events", null);
   },
};
